
const Img = {
    Home: require('../assests/icons/loc.png'),  // Correct spelling
  // draw: require('../assets/images/draw.png'),
  // primarylogo: require('../assets/images/primarylogo.png'),
  // lcn: require('../assets/images/location.png'),
  // hrt: require('../assets/images/heart.png'),
  // bll: require('../assets/images/notification.png'),
  // srch: require('../assets/images/search.png'),
  // sttng: require('../assets/images/setting.png'),
  // hstimgage: require('../assets/images/hostel.png'),
  // hstdetail: require('../assets/images/hosteldetail.png'),
  // locationdetail: require('../assets/images/locationdtl.png'),
  // verifiedicon: require('../assets/images/verified.png'),
  // ratingstaricon: require('../assets/images/ratingstar.png'),
  // noroomicon: require('../assets/images/noroom.png'),
  // allhostelicon: require('../assets/images/allhostel.png'),
  // sortbyicon: require('../assets/images/sortbyimg.png'),
  // morehostelicon: require('../assets/images/morehostel.png'),
  // hostellogoicon: require('../assets/images/hostellogo.png'),
  // hostelrentouticon: require('../assets/images/hostelrentout.png'),
  // buildingicon: require('../assets/images/build.png'),
  // pword: require('../assets/images/p.png'),
  // noitificationicon: require('../assets/images/notificationImg.png'),
  // walleticon: require('../assets/images/wallet.png'),
  // vegetableicon: require('../assets/images/vegtable.png'),
  // groceryicon: require('../assets/images/grocery.png'),
  // beautyicon: require('../assets/images/Beauty.png'),
  // householdicon: require('../assets/images/household.png'),
  // storeimgicon: require('../assets/images/storeimg.png'),
  // galleryicon: require('../assets/images/gallery.png'),
  // telegramicon: require('../assets/images/telegram.png'),
  // complainticon: require('../assets/images/complaint.png'), 
  // attachmenticon:require('../assets/images/attachment.png'),
  // tickicon:require('../assets/images/tick.png'),
  // uncheckicon:require('../assets/images/uncheck.png'),
  // helpicon:require('../assets/images/help.png'),
  // breakfasticon:require('../assets/images/breakfast.png'),
  // videoicon:require("../assets/images/video.png"),
  // hostelrentoutsucess:require("../assets/images/hostelrentoutsucess.png"),
  // profileicon:require("../assets/images/profile.png"),
  // greentick:require("../assets/images/greentick.png"),
  // lastprofileicon:require("../assets/images/lastprofile.png"),
  // bellicon:require("../assets/images/bell.png"),
  // lunchicon:require("../assets/images/lunch.png"),
  // snackicon:require("../assets/images/snack.png"),
  // lefticon:require("../assets/images/drawerarrow.png"),
};

export { Img };